# Generated by Django 4.1 on 2022-08-15 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="Оригинальный URL")),
                (
                    "url_hash",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Хэш"
                    ),
                ),
                (
                    "shorted_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Сокращённый URL"
                    ),
                ),
                (
                    "redirection",
                    models.IntegerField(default=0, verbose_name="Переходов"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель ссылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылку",
                "verbose_name_plural": "Ссылки",
                "db_table": "link",
                "ordering": ["-date"],
            },
        ),
    ]
